on:
  pull_request:
    types: [opened, reopened, closed, synchronize]
jobs:
  automate-review-app:
    runs-on: ubuntu-latest
    name: A job to create and delete review a review app
    environment:
      name: "heroku-pipeline-test-pr-${{ github.event.number }}"
      url: "https://heroku-pipeline-test-pr-${{ github.event.number }}.herokuapp.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display PR Number
        run: echo "PR ${{ github.event.number }}"
      - name: Deploy Heroku app
        uses: ./.github/actions/heroku-review-app-actions
        id: deploy
        with:
          api-key: ${{ secrets.HEROKU_API_KEY }}
          pipeline-id: ${{ secrets.HEROKU_PIPELINE_ID }}
          app-name-prefix: xalt-pipeline
          region: eu
          use-app-json: "true"
          team: puregroup
      - name: Get the review app url
        run: echo "The URL is ${{ steps.deploy.outputs.url }}"